[colors.bright]
black = "0x414868"
blue = "0x7AA2F7"
cyan = "0x7DCFFF"
green = "0x9ECE6A"
magenta = "0xBB9AF7"
red = "0xF7768E"
white = "0xC0CAF5"
yellow = "0xE0AF68"

[colors.normal]
black = "0x1E1E2E"
blue = "0x7AA2F7"
cyan = "0x7DCFFF"
green = "0x9ECE6A"
magenta = "0xBB9AF7"
red = "0xF7768E"
white = "0xA9B1D6"
yellow = "0xE0AF68"

[colors.primary]
background = "0x000000"
foreground = "0xC0CAF5"

[cursor]
style = "Underline"

[font]
size = 12.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Book"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
startup_mode = "Fullscreen"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 10

